"""add onboarding_completed and tier to users

Revision ID: b9ad90a8dada
Revises: 2f07e2177dd7
Create Date: 2026-03-21 12:56:56.909903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ad90a8dada'
down_revision: Union[str, Sequence[str], None] = '2f07e2177dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('tier', sa.String(length=20), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
