"""initial schema

Revision ID: bf6f3ae72b70
Revises: 
Create Date: 2026-03-21 10:17:18.410055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6f3ae72b70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_features_track_spotify_id'), 'audio_features', ['track_spotify_id'], unique=True)
    op.create_table('daily_listening_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_plays', sa.Integer(), nullable=True),
    sa.Column('unique_tracks', sa.Integer(), nullable=True),
    sa.Column('unique_artists', sa.Integer(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('top_genre', sa.String(length=255), nullable=True),
    sa.Column('avg_popularity', sa.Float(), nullable=True),
    sa.Column('new_artists_count', sa.Integer(), nullable=True),
    sa.Column('new_tracks_count', sa.Integer(), nullable=True),
    sa.Column('peak_hour', sa.Integer(), nullable=True),
    sa.Column('top_artist', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_stats_user_date')
    )
    op.create_index(op.f('ix_daily_listening_stats_user_id'), 'daily_listening_stats', ['user_id'], unique=False)
    op.create_table('listening_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_energy', sa.Float(), nullable=True),
    sa.Column('avg_valence', sa.Float(), nullable=True),
    sa.Column('avg_danceability', sa.Float(), nullable=True),
    sa.Column('avg_acousticness', sa.Float(), nullable=True),
    sa.Column('avg_instrumentalness', sa.Float(), nullable=True),
    sa.Column('avg_speechiness', sa.Float(), nullable=True),
    sa.Column('avg_liveness', sa.Float(), nullable=True),
    sa.Column('avg_tempo', sa.Float(), nullable=True),
    sa.Column('top_genre', sa.String(length=255), nullable=True),
    sa.Column('genre_distribution', sa.Text(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_snapshots_user_id'), 'listening_snapshots', ['user_id'], unique=False)
    op.create_table('recent_plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_spotify_id', sa.String(length=64), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=False),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('artist_spotify_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_spotify_id', 'played_at', name='uq_user_track_played')
    )
    op.create_index(op.f('ix_recent_plays_played_at'), 'recent_plays', ['played_at'], unique=False)
    op.create_index(op.f('ix_recent_plays_user_id'), 'recent_plays', ['user_id'], unique=False)
    op.create_table('track_popularity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_popularity_track_spotify_id'), 'track_popularity', ['track_spotify_id'], unique=True)
    op.create_table('user_profile_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('obscurity_score', sa.Float(), nullable=True),
    sa.Column('genre_diversity_index', sa.Float(), nullable=True),
    sa.Column('artist_loyalty_score', sa.Float(), nullable=True),
    sa.Column('listening_consistency', sa.Float(), nullable=True),
    sa.Column('total_plays_lifetime', sa.Integer(), nullable=True),
    sa.Column('total_artists_lifetime', sa.Integer(), nullable=True),
    sa.Column('total_tracks_lifetime', sa.Integer(), nullable=True),
    sa.Column('top_genres_json', sa.Text(), nullable=True),
    sa.Column('decade_distribution_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_metrics_user_id'), 'user_profile_metrics', ['user_id'], unique=True)
    op.create_table('user_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.Date(), nullable=False),
    sa.Column('top_artists_json', sa.Text(), nullable=False),
    sa.Column('top_tracks_json', sa.Text(), nullable=False),
    sa.Column('recent_plays_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'captured_at', name='uq_user_snapshot_date')
    )
    op.create_index(op.f('ix_user_snapshots_user_id'), 'user_snapshots', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.create_table('friend_invite_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_invite_links_code'), 'friend_invite_links', ['code'], unique=True)
    op.create_index(op.f('ix_friend_invite_links_user_id'), 'friend_invite_links', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('spotify_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_tokens')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_invite_links_user_id'), table_name='friend_invite_links')
    op.drop_index(op.f('ix_friend_invite_links_code'), table_name='friend_invite_links')
    op.drop_table('friend_invite_links')
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_snapshots_user_id'), table_name='user_snapshots')
    op.drop_table('user_snapshots')
    op.drop_index(op.f('ix_user_profile_metrics_user_id'), table_name='user_profile_metrics')
    op.drop_table('user_profile_metrics')
    op.drop_index(op.f('ix_track_popularity_track_spotify_id'), table_name='track_popularity')
    op.drop_table('track_popularity')
    op.drop_index(op.f('ix_recent_plays_user_id'), table_name='recent_plays')
    op.drop_index(op.f('ix_recent_plays_played_at'), table_name='recent_plays')
    op.drop_table('recent_plays')
    op.drop_index(op.f('ix_listening_snapshots_user_id'), table_name='listening_snapshots')
    op.drop_table('listening_snapshots')
    op.drop_index(op.f('ix_daily_listening_stats_user_id'), table_name='daily_listening_stats')
    op.drop_table('daily_listening_stats')
    op.drop_index(op.f('ix_audio_features_track_spotify_id'), table_name='audio_features')
    op.drop_table('audio_features')
    # ### end Alembic commands ###
